// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: invoice_service/invoice_service.proto

package invoice_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Invoice with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Invoice) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Invoice with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in InvoiceMultiError, or nil if none found.
func (m *Invoice) ValidateAll() error {
	return m.validate(true)
}

func (m *Invoice) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := InvoiceValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Number

	if m.GetAmount() <= 0 {
		err := InvoiceValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Currency

	if len(errors) > 0 {
		return InvoiceMultiError(errors)
	}

	return nil
}

// InvoiceMultiError is an error wrapping multiple validation errors returned
// by Invoice.ValidateAll() if the designated constraints aren't met.
type InvoiceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InvoiceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InvoiceMultiError) AllErrors() []error { return m }

// InvoiceValidationError is the validation error returned by Invoice.Validate
// if the designated constraints aren't met.
type InvoiceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InvoiceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InvoiceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InvoiceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InvoiceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InvoiceValidationError) ErrorName() string { return "InvoiceValidationError" }

// Error satisfies the builtin error interface
func (e InvoiceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInvoice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InvoiceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InvoiceValidationError{}

// Validate checks the field values on CreateInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInvoiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInvoiceRequestMultiError, or nil if none found.
func (m *CreateInvoiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInvoiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInvoice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInvoiceRequestValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInvoiceRequestValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInvoice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInvoiceRequestValidationError{
				field:  "Invoice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInvoiceRequestMultiError(errors)
	}

	return nil
}

// CreateInvoiceRequestMultiError is an error wrapping multiple validation
// errors returned by CreateInvoiceRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateInvoiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInvoiceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInvoiceRequestMultiError) AllErrors() []error { return m }

// CreateInvoiceRequestValidationError is the validation error returned by
// CreateInvoiceRequest.Validate if the designated constraints aren't met.
type CreateInvoiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInvoiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInvoiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInvoiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInvoiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInvoiceRequestValidationError) ErrorName() string {
	return "CreateInvoiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInvoiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInvoiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInvoiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInvoiceRequestValidationError{}

// Validate checks the field values on CreateInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateInvoiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateInvoiceResponseMultiError, or nil if none found.
func (m *CreateInvoiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateInvoiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInvoice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInvoice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateInvoiceResponseValidationError{
				field:  "Invoice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateInvoiceResponseMultiError(errors)
	}

	return nil
}

// CreateInvoiceResponseMultiError is an error wrapping multiple validation
// errors returned by CreateInvoiceResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateInvoiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateInvoiceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateInvoiceResponseMultiError) AllErrors() []error { return m }

// CreateInvoiceResponseValidationError is the validation error returned by
// CreateInvoiceResponse.Validate if the designated constraints aren't met.
type CreateInvoiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateInvoiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateInvoiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateInvoiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateInvoiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateInvoiceResponseValidationError) ErrorName() string {
	return "CreateInvoiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateInvoiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateInvoiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateInvoiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateInvoiceResponseValidationError{}

// Validate checks the field values on DescribeInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeInvoiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeInvoiceRequestMultiError, or nil if none found.
func (m *DescribeInvoiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeInvoiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DescribeInvoiceRequestMultiError(errors)
	}

	return nil
}

// DescribeInvoiceRequestMultiError is an error wrapping multiple validation
// errors returned by DescribeInvoiceRequest.ValidateAll() if the designated
// constraints aren't met.
type DescribeInvoiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeInvoiceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeInvoiceRequestMultiError) AllErrors() []error { return m }

// DescribeInvoiceRequestValidationError is the validation error returned by
// DescribeInvoiceRequest.Validate if the designated constraints aren't met.
type DescribeInvoiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeInvoiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeInvoiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeInvoiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeInvoiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeInvoiceRequestValidationError) ErrorName() string {
	return "DescribeInvoiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeInvoiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeInvoiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeInvoiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeInvoiceRequestValidationError{}

// Validate checks the field values on DescribeInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DescribeInvoiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DescribeInvoiceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DescribeInvoiceResponseMultiError, or nil if none found.
func (m *DescribeInvoiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DescribeInvoiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInvoice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DescribeInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DescribeInvoiceResponseValidationError{
					field:  "Invoice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInvoice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeInvoiceResponseValidationError{
				field:  "Invoice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DescribeInvoiceResponseMultiError(errors)
	}

	return nil
}

// DescribeInvoiceResponseMultiError is an error wrapping multiple validation
// errors returned by DescribeInvoiceResponse.ValidateAll() if the designated
// constraints aren't met.
type DescribeInvoiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DescribeInvoiceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DescribeInvoiceResponseMultiError) AllErrors() []error { return m }

// DescribeInvoiceResponseValidationError is the validation error returned by
// DescribeInvoiceResponse.Validate if the designated constraints aren't met.
type DescribeInvoiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeInvoiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeInvoiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeInvoiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeInvoiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeInvoiceResponseValidationError) ErrorName() string {
	return "DescribeInvoiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeInvoiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeInvoiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeInvoiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeInvoiceResponseValidationError{}

// Validate checks the field values on ListInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListInvoiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListInvoiceRequestMultiError, or nil if none found.
func (m *ListInvoiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListInvoiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListInvoiceRequestMultiError(errors)
	}

	return nil
}

// ListInvoiceRequestMultiError is an error wrapping multiple validation errors
// returned by ListInvoiceRequest.ValidateAll() if the designated constraints
// aren't met.
type ListInvoiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListInvoiceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListInvoiceRequestMultiError) AllErrors() []error { return m }

// ListInvoiceRequestValidationError is the validation error returned by
// ListInvoiceRequest.Validate if the designated constraints aren't met.
type ListInvoiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListInvoiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListInvoiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListInvoiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListInvoiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListInvoiceRequestValidationError) ErrorName() string {
	return "ListInvoiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListInvoiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListInvoiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListInvoiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListInvoiceRequestValidationError{}

// Validate checks the field values on ListInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListInvoiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListInvoiceResponseMultiError, or nil if none found.
func (m *ListInvoiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListInvoiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetInvoices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListInvoiceResponseValidationError{
						field:  fmt.Sprintf("Invoices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListInvoiceResponseValidationError{
						field:  fmt.Sprintf("Invoices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListInvoiceResponseValidationError{
					field:  fmt.Sprintf("Invoices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListInvoiceResponseMultiError(errors)
	}

	return nil
}

// ListInvoiceResponseMultiError is an error wrapping multiple validation
// errors returned by ListInvoiceResponse.ValidateAll() if the designated
// constraints aren't met.
type ListInvoiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListInvoiceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListInvoiceResponseMultiError) AllErrors() []error { return m }

// ListInvoiceResponseValidationError is the validation error returned by
// ListInvoiceResponse.Validate if the designated constraints aren't met.
type ListInvoiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListInvoiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListInvoiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListInvoiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListInvoiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListInvoiceResponseValidationError) ErrorName() string {
	return "ListInvoiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListInvoiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListInvoiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListInvoiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListInvoiceResponseValidationError{}

// Validate checks the field values on RemoveInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveInvoiceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveInvoiceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveInvoiceRequestMultiError, or nil if none found.
func (m *RemoveInvoiceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveInvoiceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RemoveInvoiceRequestMultiError(errors)
	}

	return nil
}

// RemoveInvoiceRequestMultiError is an error wrapping multiple validation
// errors returned by RemoveInvoiceRequest.ValidateAll() if the designated
// constraints aren't met.
type RemoveInvoiceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveInvoiceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveInvoiceRequestMultiError) AllErrors() []error { return m }

// RemoveInvoiceRequestValidationError is the validation error returned by
// RemoveInvoiceRequest.Validate if the designated constraints aren't met.
type RemoveInvoiceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveInvoiceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveInvoiceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveInvoiceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveInvoiceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveInvoiceRequestValidationError) ErrorName() string {
	return "RemoveInvoiceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveInvoiceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveInvoiceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveInvoiceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveInvoiceRequestValidationError{}

// Validate checks the field values on RemoveInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveInvoiceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveInvoiceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveInvoiceResponseMultiError, or nil if none found.
func (m *RemoveInvoiceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveInvoiceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSuccessfully

	if len(errors) > 0 {
		return RemoveInvoiceResponseMultiError(errors)
	}

	return nil
}

// RemoveInvoiceResponseMultiError is an error wrapping multiple validation
// errors returned by RemoveInvoiceResponse.ValidateAll() if the designated
// constraints aren't met.
type RemoveInvoiceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveInvoiceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveInvoiceResponseMultiError) AllErrors() []error { return m }

// RemoveInvoiceResponseValidationError is the validation error returned by
// RemoveInvoiceResponse.Validate if the designated constraints aren't met.
type RemoveInvoiceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveInvoiceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveInvoiceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveInvoiceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveInvoiceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveInvoiceResponseValidationError) ErrorName() string {
	return "RemoveInvoiceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveInvoiceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveInvoiceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveInvoiceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveInvoiceResponseValidationError{}
