// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: invoice_service/invoice_service.proto

package invoice_service

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invoice) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Invoice) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvoiceRequest) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,2,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type DescribeInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeInvoiceRequest) Reset() {
	*x = DescribeInvoiceRequest{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInvoiceRequest) ProtoMessage() {}

func (x *DescribeInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInvoiceRequest.ProtoReflect.Descriptor instead.
func (*DescribeInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeInvoiceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeInvoiceResponse) Reset() {
	*x = DescribeInvoiceResponse{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInvoiceResponse) ProtoMessage() {}

func (x *DescribeInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInvoiceResponse.ProtoReflect.Descriptor instead.
func (*DescribeInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type ListInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceRequest) Reset() {
	*x = ListInvoiceRequest{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceRequest) ProtoMessage() {}

func (x *ListInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceRequest.ProtoReflect.Descriptor instead.
func (*ListInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{5}
}

type ListInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceResponse) Reset() {
	*x = ListInvoiceResponse{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceResponse) ProtoMessage() {}

func (x *ListInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceResponse.ProtoReflect.Descriptor instead.
func (*ListInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListInvoiceResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type RemoveInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInvoiceRequest) Reset() {
	*x = RemoveInvoiceRequest{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInvoiceRequest) ProtoMessage() {}

func (x *RemoveInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInvoiceRequest.ProtoReflect.Descriptor instead.
func (*RemoveInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveInvoiceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveInvoiceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessfully bool                   `protobuf:"varint,1,opt,name=isSuccessfully,proto3" json:"isSuccessfully,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveInvoiceResponse) Reset() {
	*x = RemoveInvoiceResponse{}
	mi := &file_invoice_service_invoice_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInvoiceResponse) ProtoMessage() {}

func (x *RemoveInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_service_invoice_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInvoiceResponse.ProtoReflect.Descriptor instead.
func (*RemoveInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_service_invoice_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveInvoiceResponse) GetIsSuccessfully() bool {
	if x != nil {
		return x.IsSuccessfully
	}
	return false
}

var File_invoice_service_invoice_service_proto protoreflect.FileDescriptor

const file_invoice_service_invoice_service_proto_rawDesc = "" +
	"\n" +
	"%invoice_service/invoice_service.proto\x12\x1cturalchik.invoice_service.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\aInvoice\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"W\n" +
	"\x14CreateInvoiceRequest\x12?\n" +
	"\ainvoice\x18\x01 \x01(\v2%.turalchik.invoice_service.v1.InvoiceR\ainvoice\"X\n" +
	"\x15CreateInvoiceResponse\x12?\n" +
	"\ainvoice\x18\x02 \x01(\v2%.turalchik.invoice_service.v1.InvoiceR\ainvoice\"(\n" +
	"\x16DescribeInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Z\n" +
	"\x17DescribeInvoiceResponse\x12?\n" +
	"\ainvoice\x18\x01 \x01(\v2%.turalchik.invoice_service.v1.InvoiceR\ainvoice\"\x14\n" +
	"\x12ListInvoiceRequest\"X\n" +
	"\x13ListInvoiceResponse\x12A\n" +
	"\binvoices\x18\x01 \x03(\v2%.turalchik.invoice_service.v1.InvoiceR\binvoices\"&\n" +
	"\x14RemoveInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"?\n" +
	"\x15RemoveInvoiceResponse\x12&\n" +
	"\x0eisSuccessfully\x18\x01 \x01(\bR\x0eisSuccessfully2\xf8\x03\n" +
	"\x0eInvoiceService\x12x\n" +
	"\rCreateInvoice\x122.turalchik.invoice_service.v1.CreateInvoiceRequest\x1a3.turalchik.invoice_service.v1.CreateInvoiceResponse\x12~\n" +
	"\x0fDescribeInvoice\x124.turalchik.invoice_service.v1.DescribeInvoiceRequest\x1a5.turalchik.invoice_service.v1.DescribeInvoiceResponse\x12r\n" +
	"\vListInvoice\x120.turalchik.invoice_service.v1.ListInvoiceRequest\x1a1.turalchik.invoice_service.v1.ListInvoiceResponse\x12x\n" +
	"\rRemoveInvoice\x122.turalchik.invoice_service.v1.RemoveInvoiceRequest\x1a3.turalchik.invoice_service.v1.RemoveInvoiceResponseB>Z<github.com/Turalchik/bot/pkg/invoice_service;invoice_serviceb\x06proto3"

var (
	file_invoice_service_invoice_service_proto_rawDescOnce sync.Once
	file_invoice_service_invoice_service_proto_rawDescData []byte
)

func file_invoice_service_invoice_service_proto_rawDescGZIP() []byte {
	file_invoice_service_invoice_service_proto_rawDescOnce.Do(func() {
		file_invoice_service_invoice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoice_service_invoice_service_proto_rawDesc), len(file_invoice_service_invoice_service_proto_rawDesc)))
	})
	return file_invoice_service_invoice_service_proto_rawDescData
}

var file_invoice_service_invoice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_invoice_service_invoice_service_proto_goTypes = []any{
	(*Invoice)(nil),                 // 0: turalchik.invoice_service.v1.Invoice
	(*CreateInvoiceRequest)(nil),    // 1: turalchik.invoice_service.v1.CreateInvoiceRequest
	(*CreateInvoiceResponse)(nil),   // 2: turalchik.invoice_service.v1.CreateInvoiceResponse
	(*DescribeInvoiceRequest)(nil),  // 3: turalchik.invoice_service.v1.DescribeInvoiceRequest
	(*DescribeInvoiceResponse)(nil), // 4: turalchik.invoice_service.v1.DescribeInvoiceResponse
	(*ListInvoiceRequest)(nil),      // 5: turalchik.invoice_service.v1.ListInvoiceRequest
	(*ListInvoiceResponse)(nil),     // 6: turalchik.invoice_service.v1.ListInvoiceResponse
	(*RemoveInvoiceRequest)(nil),    // 7: turalchik.invoice_service.v1.RemoveInvoiceRequest
	(*RemoveInvoiceResponse)(nil),   // 8: turalchik.invoice_service.v1.RemoveInvoiceResponse
}
var file_invoice_service_invoice_service_proto_depIdxs = []int32{
	0, // 0: turalchik.invoice_service.v1.CreateInvoiceRequest.invoice:type_name -> turalchik.invoice_service.v1.Invoice
	0, // 1: turalchik.invoice_service.v1.CreateInvoiceResponse.invoice:type_name -> turalchik.invoice_service.v1.Invoice
	0, // 2: turalchik.invoice_service.v1.DescribeInvoiceResponse.invoice:type_name -> turalchik.invoice_service.v1.Invoice
	0, // 3: turalchik.invoice_service.v1.ListInvoiceResponse.invoices:type_name -> turalchik.invoice_service.v1.Invoice
	1, // 4: turalchik.invoice_service.v1.InvoiceService.CreateInvoice:input_type -> turalchik.invoice_service.v1.CreateInvoiceRequest
	3, // 5: turalchik.invoice_service.v1.InvoiceService.DescribeInvoice:input_type -> turalchik.invoice_service.v1.DescribeInvoiceRequest
	5, // 6: turalchik.invoice_service.v1.InvoiceService.ListInvoice:input_type -> turalchik.invoice_service.v1.ListInvoiceRequest
	7, // 7: turalchik.invoice_service.v1.InvoiceService.RemoveInvoice:input_type -> turalchik.invoice_service.v1.RemoveInvoiceRequest
	2, // 8: turalchik.invoice_service.v1.InvoiceService.CreateInvoice:output_type -> turalchik.invoice_service.v1.CreateInvoiceResponse
	4, // 9: turalchik.invoice_service.v1.InvoiceService.DescribeInvoice:output_type -> turalchik.invoice_service.v1.DescribeInvoiceResponse
	6, // 10: turalchik.invoice_service.v1.InvoiceService.ListInvoice:output_type -> turalchik.invoice_service.v1.ListInvoiceResponse
	8, // 11: turalchik.invoice_service.v1.InvoiceService.RemoveInvoice:output_type -> turalchik.invoice_service.v1.RemoveInvoiceResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_invoice_service_invoice_service_proto_init() }
func file_invoice_service_invoice_service_proto_init() {
	if File_invoice_service_invoice_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoice_service_invoice_service_proto_rawDesc), len(file_invoice_service_invoice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invoice_service_invoice_service_proto_goTypes,
		DependencyIndexes: file_invoice_service_invoice_service_proto_depIdxs,
		MessageInfos:      file_invoice_service_invoice_service_proto_msgTypes,
	}.Build()
	File_invoice_service_invoice_service_proto = out.File
	file_invoice_service_invoice_service_proto_goTypes = nil
	file_invoice_service_invoice_service_proto_depIdxs = nil
}
